repos:
  - repo: local
    hooks:
      - id: powershell-script-analyzer
        name: PowerShell Script Analyzer
        entry: pwsh
        args:
          - -NoProfile
          - -ExecutionPolicy
          - Bypass
          - -Command
          - |
            $ErrorActionPreference = 'Stop'
            $settings = Join-Path (Get-Location) 'Hawk/internal/configurations/PSScriptAnalyzerSettings.psd1'
            $files = git diff --cached --name-only --diff-filter=AM | Where-Object { $_ -match '\.(ps1|psm1|psd1)$' }
            $hasErrors = $false
            foreach ($file in $files) {
                Write-Host "Analyzing $file..."
                $results = Invoke-ScriptAnalyzer -Path $file -Settings $settings
                if ($results) {
                    $results | Format-Table -AutoSize
                    $hasErrors = $true
                }
            }
            if ($hasErrors) { exit 1 }
        language: system
        types: [powershell]
