name: "⚙️ Feature Implementation"
description: "For Hawk team members only"
title: "Implement: "
labels: ["enhancement", "internal"]
body:
  - type: input
    id: external-issue
    attributes:
      label: Related Feature Request
      description: Link to user feature request (if applicable)
      placeholder: "#123"
  - type: textarea
    id: technical-requirements
    attributes:
      label: Technical Requirements
      description: Detailed feature requirements
    validations:
      required: true
  - type: textarea
    id: implementation-approach
    attributes:
      label: Implementation Approach
      description: Technical approach and architecture changes
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Specific conditions that must be met
    validations:
      required: true
