on:
  pull_request:
    branches:
      - master
      - Development
  push:
    branches:
      - master
      - Development
      - "bugfix/117-fails-to-install-due-to-no-robustcloudcommand"
jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v1
      - name: Install Prerequisites
        run: .\build\vsts-prerequisites.ps1
        shell: powershell
      #   - name: Validate
      #     run: .\build\vsts-validate.ps1
      #     shell: powershell
      - name: Build
        run: .\build\vsts-build.ps1 -ApiKey $env:APIKEY
        shell: powershell
        env:
          APIKEY: ${{ secrets.ApiKey }}
