name: PSScriptAnalyzer
on:
  pull_request:
    paths:
      - "**.ps1"
      - "**.psm1"
      - "**.psd1"
  push:
    branches:
      - main
      - development
    paths:
      - "**.ps1"
      - "**.psm1"
      - "**.psd1"

jobs:
  analyze:
    name: PSScriptAnalyzer
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer -Force

      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          $settingsPath = ".github/psscriptanalyzer/PSScriptAnalyzerSettings.psd1"
          if (-not (Test-Path $settingsPath)) {
              Write-Error "PSScriptAnalyzer settings file not found at: $settingsPath"
              exit 1
          }

          $results = @()
          $files = Get-ChildItem -Path . -Recurse -Include *.ps1,*.psm1,*.psd1 |
                  Where-Object { $_.FullName -notlike '*\node_modules\*' }

          foreach ($file in $files) {
              Write-Host "Analyzing $($file.FullName)"
              $fileResults = Invoke-ScriptAnalyzer -Path $file.FullName -Settings $settingsPath
              $results += $fileResults
          }

          if ($results) {
              $results | Format-Table -AutoSize | Tee-Object -FilePath "psscriptanalyzer-results.txt"
              Write-Error "PSScriptAnalyzer found $($results.Count) issues"
              exit 1
          } else {
              Write-Host "No PSScriptAnalyzer issues found"
          }

      - name: Upload Results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: psscriptanalyzer-results
          path: psscriptanalyzer-results.txt
          if-no-files-found: warn
