name: Test GITHUB_TOKEN Write Access

on:
  workflow_dispatch: # Allows you to manually trigger this test

jobs:
  test-write-access:
    runs-on: ubuntu-latest
    steps:
      - name: Test GITHUB_TOKEN Write Access
        env:
          ISSUE_NUMBER: 138 # Replace with an existing issue number in your repository
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -X POST \
            -d '{"body": "Testing GITHUB_TOKEN write access"}' \
            "https://api.github.com/repos/${{ github.repository }}/issues/${ISSUE_NUMBER}/comments"
