on:
  pull_request:
    branches:
      - master
      - Development
      - bugfix/157-bug-multiple-failed-tests-after-fixing-workflow
  push:
    branches:
      - master
      - Development
jobs:
  validate:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v1
      - name: Install Prerequisites
        run: .\build\vsts-prerequisites.ps1
        shell: powershell
      - name: Validate
        run: .\build\vsts-validate.ps1
        shell: powershell
